/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CollectionGroup: typeof import('./src/components/Tabs/YourCollection/CollectionGroup.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    ItemFilters: typeof import('./src/components/Tabs/Item/ItemFilters.vue')['default']
    ItemList: typeof import('./src/components/Tabs/Item/ItemList.vue')['default']
    ItemView: typeof import('./src/components/Tabs/Item/ItemView.vue')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeChip: typeof import('primevue/chip')['default']
    PrimeDialog: typeof import('primevue/dialog')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimePaginator: typeof import('primevue/paginator')['default']
    PrimeSelect: typeof import('primevue/select')['default']
    PrimeTab: typeof import('primevue/tab')['default']
    PrimeTabList: typeof import('primevue/tablist')['default']
    PrimeTabPanel: typeof import('primevue/tabpanel')['default']
    PrimeTabPanels: typeof import('primevue/tabpanels')['default']
    PrimeTabs: typeof import('primevue/tabs')['default']
    PrimeTag: typeof import('primevue/tag')['default']
    TabContent: typeof import('./src/components/Tabs/TabContent.vue')['default']
    Tabs: typeof import('./src/components/Tabs/Tabs.vue')['default']
    ToggleDark: typeof import('./src/components/Utilities/ToggleDark.vue')['default']
    YourCollection: typeof import('./src/components/Tabs/YourCollection/YourCollection.vue')['default']
  }
}
